QupZilla/qupzilla

src/lib/cookies/cookiemanager.cpp, src/lib/cookies/cookiemanager.h, src/lib/cookies/cookiemanager.ui
So it is much simpler to remove a cookie, and get rid of a particularly offending cookie dropper site
=> Add 'Block domain' button to the cookie manager

src/lib/3rdparty/processinfo.cpp
The cmdline files opened from /proc/ were not closed if reading the data from them failed (e.g. because the file was empty). This leaked the file descriptor which could lead to failures trying to open more files later.
This fault also exists on the master branch (but the functionality is currently not used there).
Thanks!
=> Fix not closing cmdline files from /proc/ on read errors

src/lib/3rdparty/processinfo.cpp
The cmdline files opened from /proc/ were not closed if reading the data from them failed (e.g. because the file was empty). This leaked the file descriptor which could lead to failures trying to open more files later.
See #1701.
Thanks!
=> Fix not closing cmdline files from /proc/ on read errors (in master branch)

src/lib/rss/rssmanager.cpp
If the URL of an already added feed was edited to contain certain errors (e.g. a single "%") the feed could not be changed or deleted afterwards.
The fault was that edited URLs were stored in the database without being converted to a QUrl first. This conversion silently corrects some errors in the URL which also changes its value. The URLs read from the database are converted to QUrl before being set on the tabs and later are used to find entries to update or delete. This failed for edited URLs because of the now different values.
This was fixed by converting URLs from QString to QUrl before storing them in the database. Being already converted the value is then not changed if being converted again after reading and can be used for finding the entries to update or delete in the database.
=> Fix breaking RSS feed database by editing URLs

src/lib/network/schemehandlers/fileschemehandler.cpp, src/lib/network/schemehandlers/ftpschemehandler.cpp
The HTML pages created for FTP and file directory listings included the paths without escaping the HTML meta characters. The HTML generated for a path containing such characters was therefore not valid. This created problems when displaying or processing the page.
This should have been a rare problem because most paths do not contain such characters and the final display of the page (also the output from "Page Source") had most problems implicitly corrected (but not "<" followed by a letter).
Thanks!
=> Fix not escaping characters for HTML directory listings (v1.8)

src/lib/tabwidget/tabbar.cpp, src/lib/tabwidget/tabbar.h, src/plugins/TabManager/TabManager.pro, src/plugins/TabManager/tabmanagerplugin.cpp, src/plugins/TabManager/tabmanagerplugin.h, src/plugins/TabManager/tabmanagersettings.cpp, src/plugins/TabManager/tabmanagersettings.h, src/plugins/TabManager/tabmanagersettings.ui, src/plugins/TabManager/tabmanagerwidgetcontroller.cpp, src/plugins/TabManager/tabmanagerwidgetcontroller.h
- Note: in `TabBar::setVisible()` we didn't need to
check `(visible && m_window->isFullScreen())` because tabbar's
visibility in fullscreen mode is managed by m_navigationContainer.
=> TabManager: Add an option to use it as main tabbar replacement.

linux/appdata/qupzilla.appdata.xml
The id did not match the name of the .desktop file because it had a typo.
Thanks!
=> Fix id in appdata file

linux/appdata/qupzilla.appdata.xml
The id did not match the name of the .desktop file because it had a typo.
Thanks!
=> Fix id in appdata file (v1.8)

src/lib/app/mainmenu.cpp
The pages addressed with the about and qupzilla scheme can currently not be saved. This means that selecting the save entry in the file menu has no effect. To prevent users from concluding that the saving should work but actually does not, the save entry is now disabled for these schemes.
Thanks!
=> Disable save entry in menu for about and qupzilla scheme

src/lib/data/html/speeddial.html
Hiding the remove button on the last speed dial prevents an empty page.
See Issue #1753.
=> SpeedDial: Hide remove button on last speed dial

src/lib/rss/rssmanager.cpp, src/lib/rss/rssmanager.h, src/lib/rss/rssnotification.cpp
The warning dialog about duplicated RSS feeds was opened with the main application window being the parent instead of the RSS feed window. This opened the warning dialog behind the RSS feed window which was confusing because the window needed to be moved away to find and close the dialog.
Thanks!
=> Fix duplicated RSS feed dialog having wrong parent

src/lib/downloads/downloadmanager.cpp
Trying to save image file with custom name instead default one (generated from URL).
Albeit file saves with custom file name, download manager prefers default one.
=> Fix downloadmanager displaying wrong filename

src/lib/network/networkproxyfactory.cpp, src/lib/preferences/preferences.cpp, src/plugins/StatusBarIcons/sbi_networkproxy.cpp
The HttpProxy setting neither makes sense nor works without a concrete
proxy being set. So default to something that has any chance of working
without manual configuration. If you need an HTTP proxy, you will have
to configure it anyway.
=> Default to NoProxy rather than HttpProxy

BUILDING, src/defines.pri, src/install.pri
My distribution uses a prefix that is different from /usr for cross-compile capability.
However, shared data should still go to /usr/share as expected. Thus qupzilla installs to the wrong directories.
The changes fix this, so that one can now define where the data should go explicitely. If not specified it should behave like previously.
At the same time I replaced some hardcoded paths.
=> Allow to split shared data from prefix

src/lib/tabwidget/tabwidget.cpp
When trying to detach tab, having following debug output
```
Object::connect: No such signal TabbedWebView::changed() in ../../../src/lib/tabwidget/tabwidget.cpp:400
QObject::connect: (receiver name: 'tabwidget')
```
=> Fix tabwidget signals connect

src/lib/plugins/speeddial.cpp
When we click "Apply" after selecting background image, it won't be updated for already opened speed-dials. Need to open new tab to make sure background was changed.
=> Change background image instantly and for all speed dials

src/lib/bookmarks/bookmarkstoolbar.cpp
Letting Qt decide the spacing fixes the problem; and there appears to be 0 spacing anyhow.
=> fixed overlapping bookmarks on the toolbar; issue #1896

src/lib/app/browserwindow.cpp, src/lib/app/browserwindow.h
It was always starting based on:
```
int windowWidth = desktop->availableGeometry().width() / 1.3;
int windowHeight = desktop->availableGeometry().height() / 1.3;
```
because quitApp isn’t called on OS X.
=> ensured the window geometry is remembered on OS X

git_hooks/post-checkout, git_hooks/post-commit, git_hooks/post-merge, scripts/getrevision.sh
* Dev builds currently use masters commit ref and makes it difficult to determine which version is really installed with About &rarr; Help. Use the current HEAD when generating the `Makefile`s for `DGIT_REVISION`
**NOTES**
* The bash scripts are somewhat duplicated with the unused `--short` parameter but omitted at this time in case a long hash is wanted.
* `make distclean` is still needed since those defines are hard-coded into those affected `Makefile`s
=> Use `rev-parse` instead of `show-ref`

src/lib/app/profilemanager.cpp
Following mkdir is really redundant, you know.
=> Remove redundant mkdir instruction

src/plugins/GreaseMonkey/gm_script.cpp
* Eliminates some false positives
**NOTES**
* Needs further followup discussion on creator standards compliance but this is a start
---
PR READY
=> GM: Detect properly the UserScript metadata block on parse

src/plugins/GreaseMonkey/gm_script.cpp
Saving in Notepad++ with Windows line ending prevents script injection
Post fix for #1964 and some vague references at https://github.com/QupZilla/qupzilla/commit/ce67c7a455a58b3cf64491054688e4c9e9593c3a
PR NEEDS TESTING under Windows before it's ready. This is the standard GM fix which appears to be needed in Qt string handling as well... @nowrep please compile it and test under Windows before merging. *(OS X and Linux distros appear good to go)*
---
NOTE: In plain WIN7 NOTEPAD.EXE it will show up visibly as a normal looking .user.js however when NIX/OSX line endings are present it will be all on one line.
---
PR READY confirmation [here](https://github.com/QupZilla/qupzilla/commit/ce67c7a455a58b3cf64491054688e4c9e9593c3a#commitcomment-18196952) from pejakm
=> GM WIN: Add CR to detection

src/lib/app/commandlineoptions.cpp
Described at issue #2020 as requested by @nowrep.
The switch to [**QCommandLineParser**](http://doc.qt.io/qt-5/qcommandlineparser.html) forced the use of single letter for single dash command line.
So, short options like -pb for private browsing are not allowed anymore.
Since using more than a letter for short options is not possible anymore, i suggest to introduce single letter short options for any (or the most used/complex) command line option.
Ex.:
```
Options:
-h, --help                   Displays this help.
-v, --version                Displays version information.
-a, --authors                Displays author information.
-p, --profile <profileName>  Starts with specified profile.
-e, --no-extensions          Starts without extensions.
-i, --private-browsing       Starts private …
```
=> Add short command line for all options

src/lib/app/browserwindow.cpp, src/lib/app/browserwindow.h, src/lib/app/fileprinter.cpp, src/lib/app/fileprinter.h, src/lib/app/mainmenu.cpp, src/lib/lib.pro
This works by printing to PDF first, then sending the PDF to a printer if printing to a physical printer was requested.
On *nix (including Mac OS X), we use the lpr command, which is typically provided by CUPS nowadays. Currently, no options beyond the printer name are passed, there is room for improvement there. (Okular has a FilePrinter class that handles this in a more sophisticated way.)
On Windows, we use ShellExecuteW with the "printto" verb. In that case, the printer name is unfortunately the only thing that can be passed. The user experience may also be suboptimal depending on the PDF viewer installed on the system. (E.g., Adobe Reader is reported to ignore SW_HIDE.) And if there is no PDF viewer installed at all, it will of course not work at all. But it is the best we can do …
=> Add initial printing support with QtWebEngine >= 5.7.0

src/lib/app/mainapplication.cpp, src/lib/cookies/cookiemanager.cpp, src/lib/cookies/cookiemanager.ui
Changes:
Add new option in the cookie manager: "Remove cookies on exit".
Sense:
Gives the user more control over their privacy.
Notes:
New string "Remove cookies on exit" needs to be translated.
German String: "Cookies beim Beenden löschen"
Same feature for the cache would be nice.
Screenshot:
=> Added option to delete all cookies on exiting

BUILDING.md, mac/macdeploy.sh
* This fixes the missing svg icons in the menu drop-down. This is a valid issue to be addressed.
NOTE: Be sure to set the `QTDIR` environment variable to point to your platform Qt installation... **EDIT**: ... if you answer `y`es to the prompt at any time is when it is needed.
Applies to #2180 and GH labels should be modified accordingly to accommodate this Qt feature.
=> Mac: Copy missing dylib to bundle and document

src/lib/webengine/webpage.cpp
Whenever the user pressed the middle button the mouse press handler
in WebPage issued an 'execJavaScript' which has its own event loop
causing the mouse release handler to be called before the field
'm_clickedUrl' get the url in the first handler. Since this field
is used to guard the logic in the second handler the new tab wasn't
opening.
Closes #2238
=> Fixed new tab not opening on mouse mid button click

.travis.yml, appveyor.yml, mac/macdeploy.sh, mac/qt-mac-silent-install.qs, tests/autotests/autotests.pro, windows/installer.nsi
This patch add OSX build/deploy using Travis and also add integration for AppVeyor to support build/deploy under Windows. It will deploy on new tags (macOS DMG file, x86/x64 installers and installer for portable version).
To test deployed binaries [see](https://github.com/srazi/qupzilla/releases/tag/test_deploy_win_osx) (I have not tested DMG file)
Before merging you have to replace github api token by your tokens or disable deploy part.
**Windows Portable Installer:**
It is an installer that doesn't need admin rights to run and won't write to registry and also won't create an uninstaller..
=> CI for Windows and macOS

src/defines.pri
* Same feature already optional in Linux via https://github.com/QupZilla/qupzilla/blob/a71302fbc6f91aaf75ac8afca7f62227ea5ef767/git_hooks/hooks-install.sh
* Windows should probably have this too for developers but don't have MSVS installed to test and won't for quite some time.
Post followup for #1958
---
**NOTE**: PR'd to `master` so I presume it won't show up until 2.2.0
@srazi
Please take a look at this image and look at the speed dial on the Mac. It's been this way for a really long time although the broken-image image changed. I have nothing special proxy wise e.g. direct TCP/IP and clean profile. Linkage works but just no images on the Mac like there is Linux and Windows. Thanks.
=> Unix: Allow git hooks to work for development on all related nixes including Mac

.travis.yml
* Current release is OS X 10.12.4 *(Sierra)* with Xcode 8.3 *(8E162)*
* Successful make, bundle, and open with 930f1921adb9af41f77cfbac1e15184e8d49ba74 and Qt 5.8 Unified Installer installation.
Ref:
* https://docs.travis-ci.com/user/osx-ci-environment/#os-x-version
=> Mac: Version bump Travis CI OS X version

src/lib/app/browserwindow.cpp, src/lib/app/datapaths.cpp, src/lib/app/datapaths.h, src/lib/app/mainapplication.cpp, src/lib/app/mainapplication.h, src/lib/app/mainmenu.cpp, src/lib/lib.pro, src/lib/network/schemehandlers/qupzillaschemehandler.cpp, src/lib/preferences/preferences.ui, src/lib/session/restoremanager.cpp, src/lib/session/restoremanager.h, src/lib/session/sessionmanager.cpp, src/lib/session/sessionmanager.h, src/lib/tabwidget/tabwidget.cpp
***This is Session Manager as a core feature.***
1. The `$CurrentProfile/session.dat` is used as default session and a fallback for non-existing session files (on startup).
2. The `$CurrentProfile/session.dat.old` and `$CurrentProfile/session.dat.old1` are same as before i.e. backup from last active session and backup from last backup.
3. All other session files are stored in `$CurrentProfile/sessions`
4. `Open` action will open windows/tabs in current active session.
5. `Switch To` action will save current session -> close all windows ->then load selected session
6. User can not switch to backup sessions as they are overwritten by application.
7. Also deleting of backup sessions and default session is not available.
8. `Select session` is added to `after launch` that will ask about …
=> Session manager

.travis.yml, appveyor.yml
**OSX:** As we just deploy on pushing new tags so all other builds can use Homebrew qt that is a much smaller file to download.
**Windows:** As we just deploy on pushing new tags so for all other builds we don't need to make installer.
**‌Before:**
**‌After:**
=> Ci faster mac win builds

src/defines.pri, src/lib/app/mainapplication.cpp, src/lib/downloads/downloadmanager.cpp, src/lib/preferences/preferences.cpp, src/lib/webengine/webview.cpp
Check QT.webengine.VERSION in defines.pri instead of relying on QT_VERSION_CHECK. This allows using QtWebEngine 5.8 functionality on Qt 5.7.
This pull request is for v2.1 only, because master requires Qt 5.8 to begin with.
=> Support QtWebEngine 5.8 with Qt 5.7

src/lib/tools/aesinterface.cpp, src/lib/tools/aesinterface.h
Most of libcrypto and libssl internal structures were made
opaque in this version not allowing to instatiate them in
the stack.
More info:
* https://www.openssl.org/news/openssl-1.1.0-notes.html
* https://github.com/openssl/openssl/issues/962#issuecomment-208792020
=> Fixed compilation for Openssl 1.1.0

src/lib/lib.pro
Eliminates `'openssl/evp.h' file not found` #1850
😎
=> Pull Request: corrected BREW_OPENSSL path #1850

src/lib/navigation/completer/locationcompleter.cpp
This makes sure that the completer listview is properly positioned on
wayland. Tested with Qt 5.9 RC.
Closes #2344.
=> Ensure transient parent window for LocationCompleterView

src/plugins/KWalletPasswords/kwalletpasswordbackend.cpp
The .pri file for KWallet brings in the correct include path for
that framework, while KF5/KWallet/KWallet only works with a /usr/include
base dir.
=> Fix compilation with KDE in custom prefix

src/main/main.pro
when installed into a custom prefix, on Linux.
If qupzilla used cmake and ECM, this would have worked out of the box :-)
I actually volunteer to port qupzilla to cmake (qmake + env vars is rather cumbersome), but I would only test it on Linux, it would have to be tested by others on other platforms.
(Alternatively if qmake is kept, we could port to the Qt 5.8 configure system to improve upon the env var solution.)
=> Add missing RUNPATH so that qupzilla finds its shared lib

src/lib/app/mainapplication.cpp, src/lib/other/registerqappassociation.cpp, src/lib/other/registerqappassociation.h, src/lib/preferences/preferences.cpp
The main part of this patch has been taken from Firefox source code ([here](https://github.com/mozilla/gecko-dev/blob/master/browser/components/shell/nsWindowsShellService.cpp#L364)) that is licensed under MPL-2.0. Is it OK merging MPL code into GPL code?
I tested it under Windows 10 and WIndows server 2012 (that has same API like win8).
=> Windows: At first try to show native default app settings UI (>=Vista).

src/lib/3rdparty/processinfo.h
Cleanup the includes:
QtGlobal is not needed - already pulled in by qzcommon.h
QString not needed, already pulled in by qzcommon.h
Move the qzcommon include before the ifdefs
This is a change that has been getting used when building QupZilla on FreeBSD for several years now and works fine.
I was reviewing the FreeBSD port in preparation for the switchover to the new repository/name and discovered this patch. After a quick review that this patch is nothing FreeBSD-specific (just some C/C++ cleanup), I wanted to ensure this got submitted upstream ASAP.
I was originally going to submit this to the new Falkon repository, but after a fair bit of time in the KDE docs I am still unable to figure out how contributors are supposed to be able to send in patches (even with a ton of experience with …
=> Cleanup processinfo.h includes

src/lib/lib.pro, src/lib/tabwidget/tabbar.cpp, src/lib/tabwidget/tabbar.h, src/lib/tabwidget/tabcontextmenu.cpp, src/lib/tabwidget/tabcontextmenu.h, src/lib/tabwidget/tabwidget.cpp, src/lib/webtab/webtab.cpp, src/lib/webtab/webtab.h, src/plugins/TabManager/tabmanagerdelegate.cpp, src/plugins/TabManager/tabmanagerplugin.cpp, src/plugins/TabManager/tabmanagerwidget.cpp, src/plugins/TabManager/tabmanagerwidget.h, src/plugins/TabManager/tabmanagerwidget.ui, src/plugins/TabManager/tabmanagerwidgetcontroller.cpp, src/plugins/TabManager/tabmanagerwidgetcontroller.h
1- Add tab context-menu to item context-menu.
2- Scroll to the current item.
3- Use a different color for non-loaded tabs.
4- Support moving tabs by drag-n-drop (just in `Group by Window` mode).
~~`Known issue:` Draging a tab between non-loaded tabs force them to load.~~
`Update:` The known issue was fixed by adb54dcfcc2f5ac24bb41d428006004956617bac
=> Improve TabManager

mac/macdeploy.sh
* Now that upstream Qt has support for this back out the changes.
NOTE(S)
* Please note that users with Qt 5.9.0 and earlier on MacOS the bug will reappear... so minimum Qt build should be 5.9.1 if those icons in the dropdown menus are wanted
Ref(s):
* https://github.com/QupZilla/qupzilla/pull/2184#issuecomment-308790083
=> Mac: Revert #2184 for Qt 5.9.1+

.travis.yml
* Current release is OS X 10.12.6 *(Sierra)* with Xcode 9.0 *(Sep 21, 2017)*
* Successful make, bundle, and open with 4c3ef116045e1e8f63427330337dc05b3bea9e12 and Qt 5.9.2 release Unified Installer installation.
Ref:
* https://docs.travis-ci.com/user/reference/osx/
Note(s):
* Xcode 9.1 not available in the App Store yet... so not sure how Travis CI is getting this.
=> Version bump Travis CI OS X version

src/lib/other/clearprivatedata.cpp
Qt uses a 'Local Storage' directory to store web contents
whereas QupZilla tries to delete 'LocalStorage' directory
when the 'Delete locally stored content' option is set.
Closes #2472
=> Clearing correct local storage directory

linux/applications/org.qupzilla.QupZilla.desktop
This fixes various system integration things for when WM_CLASS and
WM_NAME don't match, some desktop enviroments handle this
better than others. This fixes:
* The application appearing twice in docks
* No pin to panel option shown in Budgie Desktop
* The themed icon not being used in certain situations.
Signed-off-by: Joey Riches <josephriches@gmail.com>
=> linux: add 'StartupWMClass' to desktop file

linux/appdata/org.qupzilla.QupZilla.appdata.xml
The default screenshot in appdata file (https://www.qupzilla.com/screens/gnome.png) does not exist. Redirects to https://www.qupzilla.com/home.
=> Default screenshot in appdata does not exist.

linux/appdata/org.qupzilla.QupZilla.appdata.xml, src/install.pri
Probably someone will contact you from Debian or Fedora at some point for this minor issue. The new directory for appdata is now /usr/share/metainfo. Refs:
https://fedoraproject.org/wiki/Packaging:AppData
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
https://wiki.debian.org/AppStream/Guidelines
=> Use new AppData directory instead of legacy.

mac/create_dmg.sh
* `osascript` deletes the icns file after completion for no apparent reason in High Sierra
* Move `iconutil` after this event
NOTE:
* This shouldn't cause a regression in older OS X's
=> Mac: Repair missing hidden `.VolumeIcon.icns`

src/lib/tabwidget/tabstackedwidget.cpp
Pinning/ Unpinning tabs failed to show tabToolTip in the current session so fixed that
=> fixed tabToolTip on pinning/unpinning

src/lib/data/html/speeddial.html
The current speed dial of Qupzilla shows cursor as pointer even when there is no speeddial box under it. This creates a consufion of a link there sometimes. - So I removed that preserving "cursor:pointer" on other elements
=> removed unnecessary cursor:pointer from the body of speeddial

src/lib/tabwidget/tabbar.cpp, src/lib/webtab/webtab.cpp
If the tab is not restored then, restore it and load the dropped url
=> fixed drop url over unrestored tabs
